### ISSUE TITLE
(Database) Account Error. 

### ISSUE THREAD

**Issue by JohnathanUnknown** [JohnathanUnknown/mf0DJnN#11]
*Tested.* 

Apparently, when you try to enter your regular account/password for the game, it doesn't acknowledge your current account in the database. It creates a new one with *no* toons on it. 

Even worse, it corrupts your current account on the server too. It overwrites your toons on there with the new data from this "new account" that was registered. Server will be down until this issue is fixed, it has resulted in numerous database resets and wrecked havoc. 

*Priority: High.*

**Comment by MrExternal** [comment]
*Update #1: Database Reset.*

Database has been reset, since accounts have been overwritten and they serve no purpose. Server will re-open when a database patch has been committed.

**Comment by NickdogeGaming** [comment]
Fixed.

**Comment by MrExternal** [comment]
Update 2:

Issue has resurfaced with new information, Nickdoge is assigned.

**Comment by ponyboy837** [comment]
Issue has resurfaced

**Comment by JohnathanUnknown** [comment]
@ponyboy837 Yes, we are aware. 

It appears to be with the new Astron we are using, which is different from the 2014 Astron that originally came with the source. If it isn't that, probably the ClientServicesManager acting up again..

**Comment by ponyboy837** [comment]
Actually. It's dev-accounts.db After deleting that and resetting some of the database by hand it worked again.

**Comment by JohnathanUnknown** [comment]
Did you *specifically* test what the core issue was with the database?

**Comment by JohnathanUnknown** [comment]
If you didn't see #16, it specifically states that the overwrite occurs after a specific period of time. 

It also seemed to occur after adding the newer Astron, which *also* narrows it down.

**Comment by ponyboy837** [comment]
It was like that quote exactly.

**Comment by JohnathanUnknown** [comment]
So you tested your fix against this error, and it worked?

**Comment by ponyboy837** [comment]
Yeah.

**Comment by JohnathanUnknown** [comment]
Interesting.. Would you submit a pull request with this fix and I'll take a look at it myself?

**Comment by ponyboy837** [comment]
I will when i get the time.

**Comment by JohnathanUnknown** [comment]
@ponyboy837 We already did the fix, just copied what you said you did.
