### ISSUE TITLE
Database Overwrite (cont from #11)

### ISSUE THREAD

**Issue by TTUDEV** [JohnathanUnknown/mf0DJnN#16]
*Yes, we thought we solved this issue but I guess not.* 

The database issue has returned and has continued to overwrite accounts, only this time we have new information relating to the issue. 

Seemingly, the database doesn't appear to recognize the old account information, and treats it as if there is no account with that name. It creates a new account, overwrites the other toons, and takes over as the primary account until the overwrite happens again. 

Oh, and deleting the new account and attempting to log in will only force eject you from the game when attempting to connect. This is a serious issue that needs to be fixed either today or tomorrow. 

Nickdoge is in charge of hunting this issue and taking it down for good.

**Comment by JohnathanUnknown** [comment]
Fixed, hopefully.
