### ISSUE TITLE
Connection Issues and Broken Code.

### ISSUE THREAD

**Issue by ponyboy837** [JohnathanUnknown/mf0DJnN#17]
Nice Broken Code Guys. Most of the stuff needs a hella loads of modifications to RUN!

My god.

**Comment by JohnathanUnknown** [comment]
@ponyboy837 Personally, we are aware of the source being *extremely* broken. 

This is why I should add to the README that the source is unstable. However, for the most part the *current version* of the repository is 100% working, as confirmed by me and the other developers. 

We *are* aware of database issues, and that ClientServicesManagerUD is extremely buggy and needs rewritten. We understand your impatience, but we are working on this as quick as we can.

**Comment by Grant11** [comment]
@ponyboy837 its because you don't have the correct Panda you retard. With the correct panda every thing works just fine

**Comment by JohnathanUnknown** [comment]
https://drive.google.com/file/d/0B7jVzEZjzgF2ZUw4SEJNb2VXZjQ/view @ponyboy837 

Simply download this, and place it to the C: drive. 
Make sure your PPYTHON_PATH goes to the place you put the Panda version, otherwise it'll cause issues. 

*As I said earlier, database/connection issues can happen. So keep an eye out for that when running the source code.*

**Comment by ponyboy837** [comment]
I did?  I found this repository link from the panda3D one. It's errors in your .py code.  I got it working after some time but im just sayin.

**Comment by JohnathanUnknown** [comment]
I don't see how it relates to errors in the .py code.. 

We had zero trouble getting the source to run with the Panda copy in the repository, no work was needed.

**Comment by ponyboy837** [comment]
Well that's on your side. Git mus of fuck up cloning if some of your code isn't faulty..

**Comment by JohnathanUnknown** [comment]
Must've, because we're hosting the server right now *with the current repository code.*

0 errors.
