### ISSUE TITLE
Crash when Shuffling a Color in the Make-A-Toon

### ISSUE THREAD

**Issue by ToontownMango** [JohnathanUnknown/mf0DJnN#19]
http://pastebin.com/3d6KxG1B 
pls

**Comment by ToontownMango** [comment]
Its not a BIG deal but I just wanted to let you niggers know <3

**Comment by JohnathanUnknown** [comment]
Hmm, interesting.

@NickdogeGaming Might wanna peak at this.

**Comment by NickdogeGaming** [comment]
newGloveColorIndex = colorList.index(newChoice[3])
@Weirdodude101 cough cough

**Comment by Weirdodude101** [comment]
This is now fixed.

**Comment by KingDogg** [comment]
yyjhyhjfhy
